# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='Abc', max_length=100),
            preserve_default=False,
        ),
    ]
